version: "3.5"
services:
  code-agent:
    image: explorviz/code-agent-jvm:mr-4
    networks:
      - explorviz
    volumes:
      - ./.analysis-data:/home/jboss/analysis-data
    environment:
      - ANALYSIS_REMOTE_URL=https://github.com/spring-projects/spring-petclinic
      - ANALYSIS_SEND_TO_REMOTE=false
      - EXPLORVIZ_LANDSCAPE_TOKEN=mytokenvalue
      - EXPLORVIZ_LANDSCAPE_SECRET=mytokensecret
      - ANALYSIS_APPLICATION_NAME=petclinic
      - ANALYSIS_SOURCE_DIRS=src/main/java
      - ANALYSIS_RESTRICT_DIRS=src/main/java
      - ANALYSIS_END_COMMIT=7ff5e857fdb41a9f3e012c56390c2baa1f8b0f3e

networks:
  explorviz:
    name: explorviz
