version: "3.5"
services:
  code-agent:
    image: explorviz/code-agent-jvm:mr-4
    networks:
      - explorviz
    environment:
      - ANALYSIS_REMOTE_URL=https://github.com/spring-projects/spring-petclinic
      - ANALYSIS_SEND_TO_REMOTE=true
      #- GRPC_HOST=host.docker.internal
      - GRPC_HOST=code-service
      - GRPC_PORT=9000
      - EXPLORVIZ_LANDSCAPE_TOKEN=mytokenvalue
      - EXPLORVIZ_LANDSCAPE_SECRET=mytokensecret
      - ANALYSIS_APPLICATION_NAME=petclinic
      - ANALYSIS_BRANCH=main
      - ANALYSIS_SOURCE_DIRS=src/main/java
      - ANALYSIS_RESTRICT_DIRS=src/main/java
      - EXPLORVIZ_LOG_LVL=DEBUG
      - ANALYSIS_END_COMMIT=f48227aea0e4056e1b9105494ea2f6360f3975f3

networks:
  explorviz:
    name: explorviz
