version: "3.5"
services:
  code-agent:
    image: explorviz/code-agent-jvm:mr-4
    networks:
      - explorviz
    environment:
      - ANALYSIS_REMOTE_URL=https://github.com/spring-projects/spring-petclinic
      - ANALYSIS_SEND_TO_REMOTE=true
      #- GRPC_HOST=host.docker.internal
      - GRPC_HOST=code-service
      - GRPC_PORT=9000
      - EXPLORVIZ_LANDSCAPE_TOKEN=mytokenvalue
      - EXPLORVIZ_LANDSCAPE_SECRET=mytokensecret
      - ANALYSIS_APPLICATION_NAME=petclinic
      - ANALYSIS_SOURCE_DIRS=src/main/java
      - ANALYSIS_RESTRICT_DIRS=src/main/java
      #- ANALYSIS_END_COMMIT=521d01db950e357cf81ef78c50daf290e92b309c

networks:
  explorviz:
    name: explorviz
