version: "3.5"
services:
  code-agent:
    image: explorviz/code-agent-jvm:mr-4
    networks:
      - explorviz
    volumes:
      - ./.analysis-data:/home/jboss/analysis-data
    environment:
      - ANALYSIS_REMOTE_URL=https://github.com/spring-projects/spring-petclinic
      - ANALYSIS_SEND_TO_REMOTE=false
      - EXPLORVIZ_LANDSCAPE_TOKEN=mytokenvalue
      - EXPLORVIZ_LANDSCAPE_SECRET=mytokensecret
      - ANALYSIS_APPLICATION_NAME=petclinic
      - ANALYSIS_SOURCE_DIRS=src/main/java
      - ANALYSIS_RESTRICT_DIRS=src/main/java
      - ANALYSIS_END_COMMIT=521d01db950e357cf81ef78c50daf290e92b309c

# Explanation: This compose file starts the code agent and exports the file reports and
# commit reports as JSON file in the hidden folder ./.analysis-folder. The end commit is the
# first commit of the PetClinic that includes the package structure src/main/java, since there
# it was first refactored.
# https://github.com/spring-projects/spring-petclinic/commits/main/src/main/java?after=516722647ae474746a84c197127e323135907d57+174

networks:
  explorviz:
    name: explorviz
